version: 2

project_name: go-xdr

before:
  hooks:
    - go mod tidy
    - sh -c "cd tools/xdrgen && go build -o ../../bin/xdrgen ."
    - sh -c "PATH=$PWD/bin:$PATH go generate ./..."

builds:
  - id: xdrgen
    main: .
    binary: xdrgen
    dir: ./tools/xdrgen
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}

archives:
  - id: xdrgen
    name_template: "xdrgen_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "merge conflict"
      - Merge pull request
      - Merge branch
      - go mod tidy
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: Bug fixes
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Others
      order: 999

release:
  github:
    owner: tempusfrangit
    name: go-xdr
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
  header: |
    ## xdrgen {{.Version}}

    XDR utility for generating XDR code.

    ### Installation

    ```bash
    go install github.com/tempusfrangit/go-xdr/tools/xdrgen@{{.Version}}
    ```

  footer: |
    ### Checksums

    All binaries are checksummed and the checksum file is signed.
