// Code generated by xdrgen. DO NOT EDIT.
// Source: /Users/m/skratch/go-xdr/void_union_test.go
// Generated: 2025-07-12T21:27:08-07:00

package xdr_test

import (
	"fmt"
	"github.com/tempusfrangit/go-xdr"

)

func (v *VoidOperation) Encode(enc *xdr.Encoder) error {

	if err := enc.EncodeUint32(uint32(v.OpCode)); err != nil {
		return fmt.Errorf("failed to encode OpCode: %w", err)
	}

	// Switch based on key for union field Data
switch v.OpCode {


	default:
		// unknown key - encode nothing

}

	return nil
}
func (v *VoidOperation) Decode(dec *xdr.Decoder) error {

	tempOpCode, err := dec.DecodeUint32()
	if err != nil {
		return fmt.Errorf("failed to decode OpCode: %w", err)
	}
v.OpCode = VoidOpCode(tempOpCode)

	// Switch based on key for union field Data
switch v.OpCode {


	default:
		// unknown key - decode nothing

}

	return nil
}
var _ xdr.Codec = (*VoidOperation)(nil)

