//go:build ignore

// Code generated by xdrgen. DO NOT EDIT.
// Source: /Users/m/skratch/go-xdr/codegen_test/alias_chain_test/referencer/referencer.go
// Generated: 2025-07-21T15:31:20-07:00

package referencer

import (
	"fmt"
	"github.com/tempusfrangit/go-xdr"
)

func (v *Referencer) Encode(enc *xdr.Encoder) error {

	if err := enc.EncodeBytes([]byte(v.Referenced)); err != nil {
		return fmt.Errorf("failed to encode Referenced: %w", err)
	}

	return nil
}

func (v *Referencer) Decode(dec *xdr.Decoder) error {

	tempReferenced, err := dec.DecodeBytes()
	if err != nil {
		return fmt.Errorf("failed to decode Referenced: %w", err)
	}
	v.Referenced = Referenced(tempReferenced)

	return nil
}

var _ xdr.Codec = (*Referencer)(nil)
