// Code generated by xdrgen. DO NOT EDIT.
// Source: /Users/m/skratch/go-xdr/codegen_test/void_cases_test.go
// Generated: 2025-07-13T16:16:59-07:00

package codegen_test

import (
	"fmt"
	"github.com/tempusfrangit/go-xdr"

)

func (v *AllVoidUnion) Encode(enc *xdr.Encoder) error {

	if err := enc.EncodeUint32(uint32(v.Status)); err != nil {
		return fmt.Errorf("failed to encode Status: %w", err)
	}

	// Switch based on key for union field Data
switch v.Status {


	default:
		// unknown key - encode nothing

}

	return nil
}
func (v *AllVoidUnion) Decode(dec *xdr.Decoder) error {

	tempStatus, err := dec.DecodeUint32()
	if err != nil {
		return fmt.Errorf("failed to decode Status: %w", err)
	}
v.Status = StatusCode(tempStatus)

	// Switch based on key for union field Data
switch v.Status {


	default:
		// unknown key - decode nothing

}

	return nil
}
var _ xdr.Codec = (*AllVoidUnion)(nil)

